### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Henri-J-Norden** [victorafael-com/UnityGradient#1]
Hi!
This is a very nice project to remove the 8-key limitation of Unity's built-in gradient.

Could you include a license in your repo so I (and others) could use it in their projects? E.g. https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt

Best regards,
Henri

**Comment by GlowlightUltro** [comment]
Joining the choir!

Mr. Rafael, your UnityGradient solution is the only one available on the internet that saves properly. Please include a license, so we can all benefit from this fantastic project. Or make an asset I can buy :)

Best regards,
Jonas

**Comment by victorafael-com** [comment]
Sorry for the delay! the license was added.
